- name: password in shell history
  hosts: all
  gather_facts: true
  remote_user: root
  tasks:
    - name: create the history file
      ansible.builtin.copy:
        dest: /home/lowpriv/.bash_history
        owner: lowpriv
        group: lowpriv
        mode: '0660'
        content: |
          ls
          cat .bash_history 
          echo 'aim8Du7h' | su whoami
          echo 'aim8Du7h' | su -S whoami
          echo 'aim8Du7h' | su - ls
          echo 'aim8Du7h' | su root
          expect
          sudo apt install expect
          su
          expect -c 'spawn ssh root@127.0.0.1 ; expect "password:"; send "aim8Du7h\r"; interact'
          history
          sshpass -p aim8Du7h ssh root@localhost
          history
          exit
