---
- name: perform basic system setup
  hosts: all
  gather_facts: true
  remote_user: root
  tasks:
    - name: update packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
    - name: "add test user 'lowpriv' with password 'trustno1'"
      user:
        name: lowpriv
        password: "$6$PA4G/HgbK6q3pqR8$UMh7rQ51EW8VBKYs00MYZgvZP/AuLXRb99h5JUbaGm3xuHW4Z39Yv1FrkllSlWeGqU6pQvdOh/s4/rKKbw4fm1"
    - name: "set root password to 'aim8Du7h'"
      user:
        name: 'root'
        password: "{{ 'aim8Du7h' | password_hash('sha512') }}"
